import Layout from "@pages/layout";
import Head from "next/head";
import { useRouter } from "next/router";
import { useUnitQuery } from "hooks/queries";
import { useTokenStore } from "stores/tokenStore";
import Catalog from "../catalog";
import Unit from "./unit";

export default function Home() {

const router = useRouter();
const {token} = useTokenStore();

const { data, isLoading} = useUnitQuery(token, Number(router.query.id));

if (isLoading)
return (
  <div>is loading ...</div>
);


return (
  <>
      <Head>
          <title>Admin | ServExpert</title>
          <meta
              name="description"
              content="Generated by create next app"
          />
          <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
          />
          <link rel="icon" href="/favicon.ico" type="image/ico" />
          <meta name="theme-color" content="rgba(0, 95, 249, 1)" />
      </Head>
      <main>
      <Layout><Catalog><Unit id={Number(router.query.id)} oldName={data === undefined || data.data === undefined || data.data.name === undefined ? '' : data.data.name} 
        oldShortName={data === undefined || data.data === undefined || data.data.shortName === undefined ? '' : data?.data.shortName} /></Catalog></Layout>
      </main>
  </>
);

};