import Head from "next/head";
import Catalog from "./catalog";
import Layout from "../layout";
import Empty from "./empty";

export default function Home() {
    return (
        <>
            <Head>
                <title>Admin | ServExpert</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" type="image/ico" />
                <meta name="theme-color" content="rgba(0, 95, 249, 1)" />
            </Head>
            <main>
            <Layout><Catalog><Empty/></Catalog></Layout>
            </main>
        </>
    );
}
