import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Image from "next/image";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import Button from "ui/components/Button";

export default function Page404() {
    const { t } = useTranslation("404");

    const router = useRouter();

    return (
        <>
            <Head>
                <title>404 | ServExpert</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" type="image/ico" />
                <meta name="theme-color" content="rgba(0, 95, 249, 1)" />
            </Head>
            <main className="w-[100vw] h-[100vh] overflow-hidden">
                <div className="w-[100vw] h-[100vh] overflow-hidden bg-white flex items-center justify-center flex-col">
                    <div className="xxl:w-[1110px] xl:w-[896px] lg:w-[476px] md:w-[476px] sm:w-[288px] relative xxl:h-[510px] xl:h-[412px] lg:h-[220px] md:h-[220px] sm:h-[132px]">
                        <Image
                            src="/assets/Images/404/404.svg"
                            alt=""
                            fill
                            style={{
                                objectFit: "cover",
                            }}
                        />
                    </div>
                    <div className="relative w-[130vw] h-[0px] z-[1] flex justify-between sm:hidden">
                        <Image
                            src="/assets/Images/404/wire.png"
                            alt=""
                            fill
                            className="relative xxl:h-[474px] top-[-150px] md:top-[300px] xl:h-[300px] lg:h-[192px] md:h-[143px] xxl:w-[843px] xl:w-[532px] lg:w-[340px] md:w-[254px] sm:w-[167px]"
                        />
                        <Image
                            src="/assets/Images/404/wire.png"
                            alt=""
                            fill
                            className="relative right-[-50vw] top-[-150px] md:top-[300px] xxl:h-[474px] xl:h-[300px] lg:h-[192px] md:h-[143px] xxl:w-[843px] xl:w-[532px] lg:w-[340px] md:w-[254px] sm:w-[167px]"
                            style={{
                                transform: "scaleX(-1)",
                            }}
                        />
                    </div>
                    <div className="z-10 xxl:w-[656px] xl:w-[728px] lg:w-[476px] md:w-[352px] sm:w-[90vw] text-center">
                        <h1 className="mb-4 text-center">{t("header_404")}</h1>
                        <p className="mb-8 body">{t("subheader_404")}</p>
                        <div>
                            <Button
                                onClick={() => {
                                    router.push("/");
                                }}
                            >
                                {t("button_404")}
                            </Button>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}

export const getStaticProps = async ({ locale }: { locale: string }) => ({
    props: {
        ...(await serverSideTranslations(locale ?? "ru")),
    },
});
