import Head from "next/head";
import { useEffect } from "react";
import { useTokenStore } from "stores/tokenStore";
import { getEmployee } from "hooks/authLogic";
import Layout from "./layout";
import Child from "./child";

  

export default function Home() {
    const {token, employeeName, setToken, setUserId, setRole, setEmployeeId, setEmployeeName} = useTokenStore();
    
    useEffect(() => {
        setToken("eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInN1YiI6IjI3IiwiaWF0IjoxNzAwMzk0MzU4LCJleHAiOjE3MDEyNTgzNTh9.9eq9eq_aEw-IIvHk-455bbWul-vrLgjtGNjqURV91Oc");
         if (token !== undefined && token !== null) {
            getEmployee(token)
            .then(
             (res) => {
               if (res !== undefined) {
                setUserId(res.userId);
                setRole("Admin");
                setEmployeeId(res.id);
                setEmployeeName(res.lastName);
               } 
               console.log(employeeName);
             }
           )
         }
        
      }, [])
      
    return (
        <>
            <Head>
                <title>Admin | ServExpert</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" type="image/ico" />
                <meta name="theme-color" content="rgba(0, 95, 249, 1)" />
            </Head>
            <main>
                <Layout><Child/></Layout>
            </main>
        </>
    );
}